pipeline {
  agent any
  stages {
    stage("import library") {
      steps {
        script {
          slack = load "${pwd()}/lib/slack.groovy"
          withCredentials([string(credentialsId: 'test_ari_git', variable: 'token')]) {
            slack.notify_message("#hooktest", token, "hello world")
          }
        }
      }
    }
    stage("echo message") {
      steps {
        echo "aaa"
      }
    }
  }
}