def transMasterTag = null
pipeline {
  agent {node { label 'master' }}
  parameters {
    booleanParam(name: 'IS_DEPLOY_APP', defaultValue: true, description: 'アプリデプロイを実行するか')
    booleanParam(name: 'IS_UPDATE_DATA', defaultValue: true, description: 'マスターアップデートを実行するか')
    string(name: 'ENV', description: 'PLAN環境選択')
    string(name: 'BRANCH', description: 'ブランチ名')
    text(name: 'MASTER_TAGS', description: 'マスタータグ')
  }
  stages {
    stage("ロック処理") {
      steps {
        script {
          def lock = load("lib/lock.groovy")
          if (lock.isLocked(params.ENV)) {
            def slack = load("lib/slack.groovy")
            def template = load("lib/template.groovy")
            message = template.getSafetyError("SFY006")
            slack.notifyMessage("planner_channel", message)
            error(message)
          }
          lock.doLock(params.ENV)
        }
      }
    }
    stage("入力チェック") {
      steps {
        script {
          def parameterValidate = load("lib/validateParameter.groovy")
          def slack = load("lib/slack.groovy")
          def template = load("lib/template.groovy")
          def errorMessages = []
          def success = null
          def errorCode = null

          if (params.IS_DEPLOY_APP == false && params.IS_UPDATE_DATA == false) {
            errorMessages.push(template.getValidateError("VLD007", 'IS_DEPLOY_APP, IS_UPDATE_DATA'))
          }
          // 環境の入力チェック
          (success, errorCode) = parameterValidate.checkExistsPlanEnv(params.ENV)
          if (success == false) {
            errorMessages.push(template.getValidateError(errorCode, 'ENV'))
          }

          // ブランチの入力チェック
          (success, errorCode) = parameterValidate.checkBranch(params.BRANCH)
          if (success == false) {
            errorMessages.push(template.getValidateError(errorCode, 'BRANCH'))
          }

          // マスタータグの入力チェック
          if (params.IS_UPDATE_DATA) {
            (success, _transMasterTag, errorCode) = parameterValidate.checkMasterTags(params.MASTER_TAGS)
            if (success == false) {
              errorMessages.push(template.getValidateError(errorCode, 'MASTER_TAGS'))
            }
            transMasterTag = _transMasterTag
          }

          if (errorMessages.size() > 0) {
            message = template.getValidateAllError(errorMessages)
            slack.errorMessage('planner_channel', message)
            error(message)
          }
        }
      }
    }
    
    stage("マスターデータ更新") {
      steps {
        script {
          if (params.IS_UPDATE_DATA) {
            def parameters = [
              [
                $class: 'StringParameterValue',
                name: 'ENV',
                value: params.ENV
              ],
              [
                $class: 'StringParameterValue',
                name: 'BRANCH',
                value: params.BRANCH
              ],
              [
                $class: 'StringParameterValue',
                name: 'MASTER_TAGS',
                value: transMasterTag
              ]
            ]
            try {
              build job: 'マスターデータ更新', parameters: parameters
            } catch(Exception e) {
              def slack = load("lib/slack.groovy")
              def template = load("lib/template.groovy")
              message = template.getSafetyError('SFY004')
              slack.errorMessage("admin_channel", message)
              slack.errroMessage("planner_channel", message)
              error(message)
            } 
          }
        }
      }
    }
    stage("アプリバージョン更新") {
      steps {
        script {
          if (IS_DEPLOY_APP) {
            def parameters = [
              [
                $class: 'StringParameterValue',
                name: 'ENV',
                value: params.ENV
              ],
              [
                $class: 'StringParameterValue',
                name: 'BRANCH',
                value: params.BRANCH
              ]
            ]
            try {
              build job: 'アプリバージョン更新', parameters: parameters
            } catch(Exception e) {
              def slack = load("lib/slack.groovy")
              def template = load("lib/template.groovy")
              message = template.getSafetyError('SFY005')
              slack.errorMessage("admin_channel", message)
              slack.errorMessage("planner_channel", message)
              error(message)
            }           
          }
        }
      }
    }
    stage("構成情報保管") {
      steps {
        script {
          // 構成ファイルをtmpから正式なディレクトリにコピーする
          def CONSTS = load("constant/main.groovy").getAll()
          dir(env.TMP_ENV_CONFIGURATION_PATH) {
            if (params.IS_DEPLOY_APP) {
              def fileName = CONSTS.PLAN_CONF_FILE_NAME.DEPLOY_APP
              sh "cp -p ${params.ENV}/${fileName} ${env.ENV_CONFIGURATION_PATH}/${params.ENV}/${fileName}"
            }
            if (params.IS_UPDATE_DATA) {
              def fileName = CONSTS.PLAN_CONF_FILE_NAME.UPDATE_DATA
              sh "cp -p ${params.ENV}/${fileName} ${env.ENV_CONFIGURATION_PATH}/${params.ENV}/${fileName}"
            }
          }
        }
      }
    }
    stage("Slackへ結果送信") {
      steps {
        script {
          def template = load("lib/template.groovy")
          def slack = load("lib/slack.groovy")
          def CONSTS = load("constant/main.groovy").getAll()

          def requestUser = ''
          wrap([$class: 'BuildUser']) {
            requestUser = BUILD_USER
          }
          def binding = [
            'request_user': requestUser,
            'target_env': params.ENV,
            'branch': params.BRANCH,
            'master_tags': params.MASTER_TAGS
          ]
          message = template.toString('success_update_plan.template', binding)
          tmeplate = null
          // TODO エラーになるので調査
          slack.notifyMessage("admin_channel", message, CONSTS)

          // try {
          //   // slack.notifyMessage("admin_channel", message)
          //   // slack.notifyMessage("planner_channel", message)
          //   def (channel, credentialsId) = CONSTS.CHANNEL_CREDENTIAL_IDS['admin_channel']
          //   withCredentials([string(credentialsId: credentialsId, variable: 'token')]) {
          //     slackSend channel: channel, token: token, message: message
          //   }
          // } catch(Exception e) {}

        }
      }
    }
  }
  post {
    always {
      script {
        def lock = load("lib/lock.groovy")
        lock.doUnlock(params.ENV)
      }
    }
  }
}