def inputParam = null
pipeline {
  agent {node { label 'master' }}
  parameters {
    string(name: 'UUID', description: 'UUID')
  }
  stages {
    stage("jsonファイルからパラメータ取得") {
      steps {
        script {
          def json = load("lib/json.groovy")
          def slack = load("lib/slack.groovy")
          try {
            def filePath = "${env.TMP_PARAMETER_PATH}/${params.UUID}.json"
            inputParam = json.read(filePath)
            // TODO (m.toga) テスト中のため一旦コメントアウト
            // json.delete(filePath)
          } catch(java.nio.file.NoSuchFileException e) {
            def slack = load("lib/slack.groovy")
            def template = load("lib/template.groovy")
            message = template.getSafetyError('SFY002')
            slack.errorMessage("admin_channel", message)
            slack.errorMessage("planner_channel", message)
            error(message)
          }
        }
      }
    }
    stage("削除処理実行") {
      steps {
        script {
          echo "削除処理実行"
        }
      }
    }
  }
  post {
  }
}