pipeline {
  agent {node { label 'master' }}
  parameters {
    string(name: 'ENV', description: 'PLANxxを指定')
  }
  stages {
    stage("環境情報の仮保存") {
      steps {
        script {
          // TODO (m.toga) ロックサンプル　後で正式に実装する
          // def lock = load("lib/lock.groovy")
          // if (lock.is_locked(params.ENV)) {
          //   def slack = load("lib/slack.groovy")
          //   // TODO (m.toga) 通知先見直す
          //   slack.notifyMessage("#hooktest", "すでに${params.ENV}は更新中のため新たに実行できません。")
          // }
          // lock.do_lock(params.ENV)
          // sh "sleep 10"

          def json = load("../${JOB_NAME}/lib/json.groovy")
          def template = load("../${JOB_NAME}/lib/template.groovy")
          def CONSTS = load("../${JOB_NAME}/constant/main.groovy").getAll()

          def rds_cluster_endpoint = 
            template.toString("plan/rds_cluster_endpoint.template", ['env': params.ENV.toLowerCase()])
          def rds_instance_endpoint = 
            template.toString("plan/rds_instance_endpoint.template", ['env': params.ENV.toLowerCase()])

          def cache_primary_endpoint = 
            template.toString("plan/cache_primary_endpoint.template", ['env': params.ENV.toLowerCase()])
          def cache_second_endpoint = 
            template.toString("plan/cache_second_endpoint.template", ['env': params.ENV.toLowerCase()])

          def cname = 
            template.toString("plan/cname.template", ['env': params.ENV.toLowerCase()])

          dir(env.TMP_ENV_CONFIGURATION_PATH) {
            sh "mkdir -p ${params.ENV}"
            json.write([
              'rds_cluster_endpoint': rds_cluster_endpoint,
              'rds_instance_endpoint': rds_instance_endpoint,
              'cache_primary_endpoint': cache_primary_endpoint,
              'cache_second_endpoint': cache_second_endpoint,
              'cname': cname
            ], "${params.ENV}/${CONSTS.PLAN_CONF_FILE_NAME.PROVISIONING}")
          }
        }
      }
    }
    stage("terraformを実行") {
      steps {
        // TODO (m.toga) あとでちゃんとしたノードを設定する
        node("master") {
          sh "echo"
        }
      }
    }
  }
  post {
    always {
      script {
        // TODO (m.toga) ロックサンプル　後で正式に実装する
        // def lock = load("lib/lock.groovy")
        // lock.do_unlock(params.ENV)
      }
    }
  }
}