@Library('auto-deploy') _

pipeline {
  agent any
  stages {
    stage("shared library import test") {
      steps {
        node("master") {
          script {
            def slack = new org.slack.Util()
            def channel = "#hooktest"
            credentialId = constant.slack.channelCredentialIds channel
            slack.notifyMessage('#hooktest', credentialId, "bbbbbb")
          }
        }
        node("master") {
          script {
            def slack = new org.slack.Util()
            // slack.notifyMessage('#hooktest', "aaaaa")
          }
        }
      }
    }
  }
}