@Library('auto-deploy') _

pipeline {
  agent any
  stages {
    stage("shared library import test") {
      steps {
        node("master") {
          script {
            def slack = new org.slack.Util()
            slack.testEcho("aaaaaaa")
          }
        }
      }
    }
  }
}