@Library("auto-deploy") _

def input_param = null
pipeline {
  agent any
  parameters {
    string(name: 'UUID', description: 'UUID')
  }
  stages {
    stage("jsonファイルからパラメータ取得") {
      steps {
        script {
          def json = new org.json.Util()
          def filePath = "${env.TMP_PARAMETER_PATH}/${params.UUID}.json"
          json.delete(filePath)
        }
      }
    }
  }
  post {
    always {
      script {
        def slack = new org.slack.Util()
        slack.notifyMessage("#hooktest", "申請が却下されました。(申請ID：${params.UUID})")
      }
    }
  }
}