pipeline {
  agent {node { label 'master' }}
  parameters {
    string(name: 'ENV', description: 'PlanXXを指定')
    string(name: 'BRANCH', description: 'ブランチを指定')
  }
  stages {
    stage("環境情報の仮保存") {
      steps {
        node("master") {
          script {
            def json = load("../${JOB_NAME}/lib/json.groovy")
            def CONSTS = load("../${JOB_NAME}/constant/main.groovy").getAll()

            json.createTmpEnvConfFile(['branch': params.BRANCH], params.ENV, CONSTS.ENV_CONF_FILE_NAME.DEPLOY_APP)
          }
        }
      }
    }
    stage("アプリデプロイ実行") {
      steps {
        // TODO (m.toga) ノードの設定は変更する必要がある
        node("master") {
          // TODO(m.toga) Windows上でsh認識するのか確認
          echo  "# /c/Jenkins/aws_deploy.sh ${params.ENV}"
        }
      }
    }
  }
}