pipeline {
  agent any
  parameters {
    string(name: 'ENV', description: 'PLANxxを指定')
    string(name: 'BRANCH', description: 'ブランチを指定')
  }
  stages {
    stage("環境情報の仮保存") {
      steps {
        script {
          def json = load("lib/json.groovy")
          def CONSTS = load("constant/main.groovy").getAll()

          dir(env.TMP_ENV_CONFIGURATION_PATH) {
            sh "mkdir -p ${params.ENV}"
            json.write([
              'branch': env.BRANCH
            ], "${params.ENV}/${CONSTS.PLAN_CONF_FILE_NAME.DEPLOY_APP}")
          }
        }
      }
    }
    stage("実行") {
      steps {
        // TODO (m.toga) ノードの設定は変更する必要がある
        node("master") {
          // TODO(m.toga) Windows上でsh認識するのか確認
          // sh "/c/Jenkins/aws_deploy.sh ${params.ENV}"
        }
      }
    }
  }
}