pipeline {
  agent {node { label 'master' }}
  parameters {
    string(name: 'ENV', description: 'PlanXXを指定')
    string(name: 'BRANCH', description: 'ブランチを指定')
    string(name: 'MASTER_TAGS', description: 'マスタータグ')
  }
  stages {
    stage("環境情報の仮保存") {
      steps {
        node("master") {
          script {
            def json = load("../${JOB_NAME}/lib/json.groovy")
            def CONSTS = load("../${JOB_NAME}/constant/main.groovy").getAll()

            def jsonData = [
              'master_tags': params.MASTER_TAGS,
              'branch': params.BRANCH
            ]
            json.createTmpEnvConfFile(jsonData, params.ENV, CONSTS.ENV_CONF_FILE_NAME.UPDATE_DATA)
          }
        }
      }
    }
    stage("データ更新") {
      steps {
        // TODO (m.toga) ノードの設定は変更する必要がある
        node("master") {
          echo "データ更新"
          // TODO (m.toga) チケットに記載されている値になっているか実行前に再度確認
          def NODE_ENV = "${params.ENV.toLowerCase()}"
          def SQL_ENV = "develop"
          echo "# /home/jenkins/AvalonServerShell/avalon_update_master.sh '${NODE_ENV}' '${SQL_ENV}' '${params.BRANCH}' '${MASTER_TAGS}'"
        }
      }
    }
  }
}