def inputParam = null
pipeline {
  agent {node { label 'master' }}
  parameters {
    string(name: 'UUID', description: 'UUID')
  }
  stages {
    stage("jsonファイルからパラメータ取得") {
      steps {
        script {
          def json = load("lib/json.groovy")
          def slack = load("lib/slack.groovy")
          def template = load("lib/template.groovy")

          try {
            def filePath = "${env.TMP_PARAMETER_PATH}/${params.UUID}.json"
            inputParam = json.read(filePath)
            json.delete(filePath)
          } catch(java.nio.file.NoSuchFileException e) {
            message = template.getSafetyError('SFY001')
            slack.errorMessage("admin_channel", message)
            slack.errorMessage("planner_channel", message)
            error(message)
          }

          def binding = [
            'uuid': params.UUID,
            'request_user': inputParam.request_user,
            'request_datetime': inputParam.request_datetime,
            'target_env': inputParam.target_env,
            'branch': inputParam.branch
          ]
          message = template.toString('refusal_create_plan.template', binding)
          // TODO エラーが出るので調査
          // slack.notifyMessage("admin_channel", message)
          // slack.notifyMessage("planner_channel", message)
        }
      }
    }
  }
}