def input_param = null
pipeline {
  agent {node { label 'master' }}
  parameters {
    string(name: 'UUID', description: 'UUID')
  }
  stages {
    stage("jsonファイルからパラメータ取得") {
      steps {
        node("master") {
          script {
            def json = load("../${JOB_NAME}/lib/json.groovy")
            def slack = load("../${JOB_NAME}/lib/slack.groovy")
            def filePath = "${env.TMP_PARAMETER_PATH}/${params.UUID}.json"
            json.delete(filePath)
            slack.notifyMessage("#hooktest", "申請が却下されました。(申請ID：${params.UUID})")
          }
        }
      }
    }
  }
}